### ISSUE TITLE
Create documentation team

### ISSUE THREAD

**Issue by jsmorabito** [athensresearch/handbook#25]
https://github.com/orgs/athensresearch/teams

Create documentation team in Github Teams to @ multiple people for docs related issues

**Comment by joelhans** [comment]
@tangjeff0 How do we best go about wrapping this TODO up? It would be awesome to enable @sawhney17 and anyone else who wants to pitch in.

I'm guessing we would need to invite anyone who isn't already on the Athens Research org, then assign them to a new **handbook** or **documentation** team? Is there a limit to how many people we can invite to the org?

I can also create a `.github/CODEOWNERS` file to make sure people on that team are assigned to any PR in this repo.

**Comment by tangjeff0** [comment]
@joelhans I just made you an admin for this repo ([highest permissions](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization)). We have an org-level @athensresearch/community team. We can also invite people at the repo-level, and keep them as an external contributor. Please see what is possible with GitHub permissions and let me know what you want to do.

**Comment by joelhans** [comment]
@tangjeff0 I've tested this out with @sawhney17 (thanks for being a test subject!) and I think adding interested people as external contributors works for now. The big challenge here is not necessarily these settings, but finding a handful of people and getting them aligned toward a common goal, which is a people problem, not a tooling one. But these roles will help enable contributors, which is the best first start. Thanks!

**Comment by elazar** [comment]
I'd love to help with this!

**Comment by joelhans** [comment]
@elazar Awesome! :100:  Just added you.

The [project board](https://github.com/athensresearch/handbook/projects/3) has all the immediate TODOs, but of course it would also be nice to get everyone together on Discord to talk about processes and identify gaps in content. Still working on a plan to make that happen.
