### ISSUE TITLE
Make the Table of Contents Explorable

### ISSUE THREAD

**Issue by Ejipuh** [athensresearch/handbook#31]
The [front page of the handbook](https://athensresearch.gitbook.io/handbook/) would be an excellent place for navigating the entire document, but the table of contents it provides has no hyperlinks. Making these clickable should be as simple as adding links to each, and would enable this navigation.

**Comment by Ejipuh** [comment]
Working on this now. (Hadn't known how to submit PRs to the handbook.)

**Comment by sawhney17** [comment]
At the moment, the front page of the handbook doesn't appear to have any missing links. Going to mark this as closed.
